import { execFileSync } from "node:child_process";
import path from "node:path";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";

// @ts-expect-error process is a nodejs global
const host = process.env.TAURI_DEV_HOST;

// https://vite.dev/config/
function readGitValue(args: string[], fallback: string): string {
  try {
    return execFileSync("git", args, { encoding: "utf8" }).trim() || fallback;
  } catch {
    return fallback;
  }
}

export default defineConfig(async () => {
  const buildId =
    process.env.VITE_ZION_BUILD_ID ??
    new Date()
      .toISOString()
      .replace(/[-:TZ.]/g, "")
      .slice(0, 12);
  const commit =
    process.env.VITE_ZION_COMMIT ??
    readGitValue(["rev-parse", "--short=12", "HEAD"], "unknown");
  const worktree =
    process.env.VITE_ZION_WORKTREE ??
    (readGitValue(["status", "--porcelain"], "") === "" ? "clean" : "dirty");

  return {
    plugins: [
      tanstackRouter({
        target: "react",
        routesDirectory: "./src/app/routes",
        generatedRouteTree: "./src/app/routeTree.gen.ts",
        virtualRouteConfig: "./src/app/routes.ts",
        quoteStyle: "double",
        semicolons: true,
        routeTreeFileHeader: [
          "// biome-ignore-all lint: generated by TanStack Router",
        ],
      }),
      react(),
    ],
    resolve: {
      alias: {
        "@": "/src",
        "@features-manifest": path.resolve(
          __dirname,
          "../preview-features.json",
        ),
      },
    },
    define: {
      "import.meta.env.VITE_ZION_BUILD_ID": JSON.stringify(buildId),
      "import.meta.env.VITE_ZION_COMMIT": JSON.stringify(commit),
      "import.meta.env.VITE_ZION_WORKTREE": JSON.stringify(worktree),
    },

    // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
    //
    // 1. prevent Vite from obscuring rust errors
    clearScreen: false,
    // 2. tauri expects a fixed port, fail if that port is not available
    server: {
      port: parseInt(process.env.VITE_PORT || "1420", 10),
      strictPort: true,
      host: host || false,
      hmr: host
        ? {
            protocol: "ws",
            host,
            port: parseInt(process.env.VITE_HMR_PORT || "1421", 10),
          }
        : undefined,
      watch: {
        // 3. tell Vite to ignore watching `src-tauri`
        ignored: ["**/src-tauri/**"],
      },
    },
  };
});
